from django.contrib import admin
from django.urls import path
from . import views
 
urlpatterns = [
    path('admin/', admin.site.urls),

    path('goal_evaluation/<int:goal_id>', views.goal_evaluation, name='goal_evaluation'),
    path('task_evaluation/<int:task_id>', views.task_evaluation, name='task_evaluation'),
    path('task_delete/<int:task_id>', views.task_delete, name='task_delete'),
    path('task_delete_page/', views.task_delete_page, name='task_delete_page'),
    path('signin/',views.signin, name='signin'),
    path('goal/',views.goal, name='goal'),
    path('signout/',views.signout, name='signout'),
    path('signup/',views.signup, name='signup'),
    path('profile/',views.profile, name='profile'),
    path('social_style/',views.social_style, name='social_style'),
    path('user_subject_record/',views.user_subject_record, name='user_subject_record'),
    path('student_pre_assessment/',views.student_pre_assessment, name='student_pre_assessment'),
    path('social_style_score/',views.social_style_score, name='social_style_score'),
    path ('goal_delete_page/',views.goal_delete_page, name='goal_delete_page'),
    path('goal_delete/<int:goal_id>',views.goal_delete, name='goal_delete'),
    path('task/',views.task, name='task'),
    path('coaching_report/',views.coaching_report, name='coaching_report'),
    path('coaching_report_entry/',views.coaching_report_entry, name='coaching_report_entry'),
    path('s_and_c_record/',views.s_and_c_record, name='s_and_c_record'),
    path('academic_coaching_record/',views.academic_coaching_record, name='academic_coaching_record'),
    path('final_evaluation/',views.final_evaluation, name='final_evaluation'),
    path('edit_personal_info/',views.edit_personal_info, name='edit_personal_info'),
    path('change_password/',views.change_password, name='change_password'),
    path('student_profile/',views.student_profile, name='student_profile'),
    path('eca/',views.eca, name='eca'),
    path('eca_delete/<int:eca_id>',views.eca_delete, name='eca_delete'),
    path('subject_grade/', views.subject_grade, name='subject_grade'),
    path('user_role/', views.user_role, name='user_role'),
    path('coach_student_select/', views.coach_student_select, name='coach_student_select'),
    path('coach_student_mapping_delete/<int:coach_id>/<int:student_id>',views.coach_student_mapping_delete, name='coach_student_mapping_delete'),
    path('reset_coach_as_student/',views.reset_coach_as_student, name='reset_coach_as_student'),
    path('qualification/',views.qualification, name='qualification'),
    path('qualification_delete/<int:qualification_id>',views.qualification_delete, name='qualification_delete'),
    path('study_method/', views.study_method, name='study_method'),
    path('study_method_add/<int:method_id>', views.study_method_add, name='study_method_add'),
    path('study_method_evaluation/<int:method_id>', views.study_method_evaluation, name='study_method_evaluation'),
    path('study_method_delete_page', views.study_method_delete_page, name='study_method_delete_page'),
    path('study_method_delete/<int:method_id>', views.study_method_delete, name='study_method_delete'),
    path('coaching_report_landing/', views.coaching_report_landing, name='coaching_report_landing'),
    path('coaching_report_edit/<int:coaching_report_id>', views.coaching_report_edit, name='coaching_report_edit'),
]