# Generated by Django 4.1 on 2023-06-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        
    ]
