# Generated by Django 4.1 on 2023-08-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0001_initial"),
    ]

    operations = [
        
    ]
